In [2]:
import pandas as pd 
import geopandas as gpd

# clean data for states

## remove columns, round numbers, and rename columns

In [68]:
df = gpd.read_file('updated_states.geojson')
df = df.drop(columns=['Exp_Current_RESA', 'id', 'density'])

In [69]:
#df = df.round(2)
df.columns = df.columns.str.replace('_', ' ')
df = df[df['name'] != 'Puerto Rico']
df = df.drop(16)
df

,name,Total Revenue,Total Fedreal Revenue,Total State Revenue,Total Local Revenue,Total Expenditure,Total Current Expenditures Education,Number of Students,Estimated Total Population,Estimated School Age Population,Estimated School Age Poverty,School Age Poverty Share,School Age Share Population,geometry
0,Alabama,1.462399e+10,2.178050e+09,7.862680e+09,4.583262e+09,1.371499e+10,1.183144e+10,1045118.0,7368282.0,1190528.0,221740.0,46.864622,35.642442,"POLYGON ((-87.35930 35.00118, -85.60667 34.984..."
1,Alaska,1.031222e+09,1.851580e+08,7.027960e+08,1.432680e+08,1.037706e+09,9.819600e+08,66356.0,249366.0,42938.0,4692.0,8.855286,7.943110,"MULTIPOLYGON (((-131.60202 55.11798, -131.5691..."
2,Arizona,1.606651e+10,2.799010e+09,6.222061e+09,7.045438e+09,1.574263e+10,1.297759e+10,1340338.0,13693867.0,1913294.0,287185.0,56.863344,43.199131,"POLYGON ((-109.04250 37.00026, -109.04798 31.3..."
3,Arkansas,9.879550e+09,1.541200e+09,4.496606e+09,3.841744e+09,9.749658e+09,8.378818e+09,766148.0,5047096.0,848330.0,152132.0,79.644082,63.900284,"POLYGON ((-94.47384 36.50186, -90.15254 36.496..."
4,California,1.205338e+11,1.545904e+10,6.633966e+10,3.873512e+10,1.116487e+11,9.345144e+10,6696239.0,53857316.0,7889224.0,1093610.0,164.130942,153.955398,"POLYGON ((-123.23326 42.00619, -122.37885 42.0..."
5,Colorado,2.478841e+10,2.894752e+09,8.999288e+09,1.289437e+10,2.531168e+10,1.974210e+10,1622434.0,11002450.0,1757406.0,166656.0,40.435328,49.294460,"POLYGON ((-107.91973 41.00391, -105.72895 40.9..."
6,Connecticut,1.541977e+10,8.285320e+08,5.938068e+09,8.653169e+09,1.509832e+10,1.309266e+10,601205.0,4782569.0,710264.0,84940.0,15.811199,28.815302,"POLYGON ((-73.05353 42.03905, -71.79931 42.022..."
7,Florida,1.683644e+10,2.477038e+09,7.383562e+09,6.975838e+09,1.628844e+10,1.398929e+10,1383334.0,10050784.0,1525838.0,264498.0,12.514716,8.195394,"POLYGON ((-85.49714 30.99754, -85.00421 31.003..."
8,Georgia,4.071936e+10,4.794070e+09,1.701869e+10,1.890659e+10,3.851428e+10,3.410084e+10,2811336.0,17676884.0,3086326.0,545788.0,67.678876,47.031520,"POLYGON ((-83.10919 35.00118, -83.32279 34.787..."
9,Hawaii,6.483780e+09,7.420360e+08,5.703528e+09,3.821600e+07,6.230530e+09,5.840182e+09,352882.0,2814012.0,423556.0,40112.0,0.189406,0.301034,"MULTIPOLYGON (((-155.63484 18.94827, -155.8813..."
10,Idaho,5.155110e+09,8.040000e+08,3.129950e+09,1.221160e+09,4.760228e+09,4.371910e+09,485388.0,3170116.0,594110.0,57594.0,20.858708,31.887992,"POLYGON ((-116.04751 49.00024, -116.04751 47.9..."
11,Illinois,4.393070e+10,2.755755e+09,1.821495e+10,2.296000e+10,4.182922e+10,3.633250e+10,1988980.0,18030339.0,2291262.0,257865.0,132.605567,151.508943,"POLYGON ((-90.63998 42.51006, -88.78878 42.493..."
12,Indiana,1.952536e+10,1.723966e+09,1.075133e+10,7.050064e+09,1.916844e+10,1.500207e+10,1478508.0,9952868.0,1699240.0,209078.0,54.488662,78.403156,"POLYGON ((-85.99006 41.75972, -84.80704 41.759..."
13,Iowa,1.290568e+10,1.200868e+09,6.159280e+09,5.545528e+09,1.235380e+10,9.576700e+09,786290.0,4957278.0,830554.0,84430.0,53.802464,95.921374,"POLYGON ((-91.36842 43.50139, -91.21506 43.501..."
14,Kansas,1.172516e+10,1.020478e+09,7.794752e+09,2.909930e+09,1.223546e+10,9.742086e+09,739500.0,4419440.0,784526.0,93310.0,57.531918,86.675036,"POLYGON ((-101.90605 40.00163, -95.30634 40.00..."
15,Kentucky,1.072448e+10,1.750852e+09,5.712201e+09,3.261432e+09,1.045450e+10,9.065961e+09,781955.0,5185711.0,842484.0,158425.0,52.589695,37.038469,"POLYGON ((-83.90335 38.76931, -83.67879 38.632..."
17,Missouri,2.026326e+10,2.382106e+09,5.825366e+09,1.205579e+10,1.891363e+10,1.566511e+10,1382664.0,9728654.0,1605111.0,222457.0,148.287372,141.702385,"POLYGON ((-91.83396 40.60957, -91.72989 40.615..."
18,Louisiana,8.872700e+09,1.427302e+09,3.299526e+09,4.145872e+09,8.427374e+09,7.646638e+09,579780.0,4030130.0,695946.0,151088.0,17.493582,12.339138,"POLYGON ((-93.60849 33.01853, -91.16577 33.002..."
19,Maine,3.962845e+09,5.531240e+08,1.750199e+09,1.659522e+09,3.877729e+09,3.293231e+09,193271.0,1643574.0,229552.0,29731.0,47.785700,42.068643,"POLYGON ((-70.70392 43.05776, -70.82441 43.128..."
20,Maryland,6.902748e+09,6.281040e+08,3.346294e+09,2.928350e+09,6.543904e+09,5.581494e+09,330540.0,2233830.0,351592.0,52496.0,1.027644,1.319426,"MULTIPOLYGON (((-75.99465 37.95325, -76.01655 ..."
21,Massachusetts,2.614188e+10,1.531935e+09,1.114413e+10,1.346582e+10,2.753332e+10,2.220756e+10,1131295.0,9089369.0,1322459.0,123469.0,27.744856,53.262292,"POLYGON ((-70.91752 42.88797, -70.81894 42.871..."
22,Michigan,3.403592e+10,3.832254e+09,1.928041e+10,1.092326e+10,3.296824e+10,2.694532e+10,2117661.0,17006856.0,2699897.0,422304.0,114.731102,129.250725,"MULTIPOLYGON (((-83.45424 41.73234, -84.80704 ..."
23,Minnesota,2.473949e+10,2.270428e+09,1.536012e+10,7.108944e+09,2.564227e+10,1.940188e+10,1423244.0,9929962.0,1692617.0,151003.0,47.497479,92.245949,"POLYGON ((-92.01470 46.70540, -92.09137 46.749..."
24,Mississippi,7.764702e+09,1.484404e+09,3.632196e+09,2.648102e+09,7.548626e+09,6.447406e+09,647156.0,4375356.0,759942.0,185176.0,56.511258,35.713144,"POLYGON ((-88.47111 34.99570, -88.20274 34.995..."
25,Montana,2.018644e+09,3.498870e+08,7.985760e+08,8.701810e+08,1.987986e+09,1.693462e+09,128127.0,1735866.0,155945.0,19786.0,60.562371,41.925138,"POLYGON ((-104.04753 49.00024, -104.04206 47.8..."
26,Nebraska,7.053926e+09,5.933860e+08,2.048716e+09,4.411824e+09,7.445788e+09,6.102828e+09,474766.0,2698808.0,483836.0,39752.0,41.648610,71.009808,"POLYGON ((-103.32458 43.00299, -101.62673 42.9..."
27,Nevada,5.215600e+08,5.425400e+07,2.323840e+08,2.349220e+08,5.091720e+08,4.600540e+08,34244.0,242368.0,37244.0,4852.0,2.451592,2.703960,"POLYGON ((-117.02788 42.00071, -114.04295 41.9..."
28,New Hampshire,4.131353e+09,2.881560e+08,1.231277e+09,2.611920e+09,3.970985e+09,3.562896e+09,187542.0,1667820.0,216855.0,16285.0,14.016660,22.108906,"POLYGON ((-71.08183 45.30330, -71.03254 44.657..."
29,New Jersey,4.741873e+10,2.383209e+09,1.991079e+10,2.512473e+10,4.588464e+10,3.885598e+10,1766761.0,13809496.0,2037363.0,235275.0,64.103321,102.345861,"POLYGON ((-74.23655 41.14083, -73.90245 40.998..."
30,New Mexico,6.458872e+09,7.438520e+08,4.647730e+09,1.067290e+09,6.366208e+09,5.413878e+09,453240.0,3411714.0,548600.0,100530.0,27.995574,18.595608,"POLYGON ((-107.42133 37.00026, -106.86816 36.9..."
31,New York,6.947752e+10,3.223279e+09,2.875991e+10,3.749433e+10,6.897822e+10,5.961190e+10,2401541.0,18113314.0,2735468.0,345208.0,128.230762,159.202538,"POLYGON ((-73.34381 45.01303, -73.33285 44.804..."
32,North Carolina,2.249958e+10,2.855564e+09,1.396918e+10,5.674844e+09,2.298931e+10,2.080854e+10,1973504.0,14689890.0,2404194.0,399098.0,28.159386,22.265890,"POLYGON ((-80.97866 36.56211, -80.29404 36.545..."
33,North Dakota,2.700608e+09,4.360870e+08,1.337121e+09,9.274000e+08,2.651327e+09,2.165167e+09,147431.0,969275.0,170300.0,16937.0,34.671679,49.486237,"POLYGON ((-97.22874 49.00024, -97.09730 48.682..."
34,Ohio,4.188700e+10,3.524552e+09,1.518204e+10,2.318041e+10,4.166614e+10,3.372298e+10,2548794.0,19078660.0,3101192.0,422234.0,130.405092,177.162992,"POLYGON ((-80.51860 41.97880, -80.51860 40.636..."
35,Oklahoma,1.383167e+10,2.020479e+09,5.951714e+09,5.859473e+09,1.385958e+10,1.209325e+10,1156506.0,7581544.0,1332207.0,224425.0,150.421903,150.826702,"POLYGON ((-100.08771 37.00026, -94.61624 37.00..."
36,Oregon,1.553115e+10,1.244555e+09,8.349825e+09,5.936770e+09,1.689767e+10,1.230326e+10,916737.0,7174069.0,1086533.0,112397.0,39.117070,44.073467,"POLYGON ((-123.21135 46.17414, -123.11824 46.1..."
37,Pennsylvania,5.061627e+10,2.997730e+09,1.807050e+10,2.954804e+10,4.969985e+10,3.914812e+10,2389368.0,19389718.0,2917770.0,333656.0,105.344152,129.463876,"POLYGON ((-79.76278 42.25265, -79.76278 42.000..."
38,Rhode Island,2.728393e+09,2.941010e+08,1.262413e+09,1.171879e+09,2.647552e+09,2.297588e+09,124329.0,1014401.0,146225.0,22838.0,3.002508,3.946234,"MULTIPOLYGON (((-71.19684 41.67757, -71.12017 ..."
39,South Carolina,1.181684e+10,1.402848e+09,5.734902e+09,4.679090e+09,1.154332e+10,9.764374e+09,771186.0,5270980.0,872537.0,160588.0,23.938644,17.677183,"POLYGON ((-82.76414 35.06690, -82.55054 35.160..."
40,South Dakota,3.178600e+09,5.648820e+08,1.018204e+09,1.595514e+09,3.043010e+09,2.544238e+09,235458.0,1518340.0,264246.0,30402.0,32.907006,43.324286,"POLYGON ((-104.04753 45.94411, -96.56056 45.93..."
41,Tennessee,1.417760e+10,1.846434e+09,6.078343e+09,6.252826e+09,1.341180e+10,1.187234e+10,1132499.0,8451660.0,1266604.0,183477.0,34.864533,27.979548,"POLYGON ((-88.05487 36.49638, -88.07130 36.677..."
42,Texas,1.202102e+11,1.396173e+10,3.867917e+10,6.756932e+10,1.290409e+11,9.519635e+10,8811387.0,52523246.0,9686201.0,1614629.0,317.658332,327.606812,"POLYGON ((-101.81294 36.50186, -100.00007 36.5..."
43,Utah,1.045192e+10,9.992240e+08,5.256666e+09,4.196032e+09,1.056460e+10,8.768984e+09,958898.0,5389484.0,1131878.0,70216.0,4.698288,10.205986,"POLYGON ((-112.16436 41.99523, -111.04706 42.0..."
44,Vermont,1.019364e+09,1.261070e+08,7.659320e+08,1.273250e+08,1.026649e+09,8.969910e+08,29658.0,630868.0,84890.0,7629.0,4.836901,6.987766,"POLYGON ((-71.50355 45.01303, -71.49260 44.914..."
45,Virginia,1.586878e+10,1.586855e+09,7.338782e+09,6.943148e+09,1.542973e+10,1.378426e+10,1093385.0,7920523.0,1205578.0,151914.0,26.588545,25.801528,"MULTIPOLYGON (((-75.39766 38.01350, -75.24430 ..."
46,Washington,2.474231e+10,1.846440e+09,1.724745e+10,5.648416e+09,2.560593e+10,2.039617e+10,1360572.0,8626980.0,1486460.0,147326.0,57.915052,70.253260,"MULTIPOLYGON (((-117.03336 49.00024, -117.0443..."
47,West Virginia,3.895688e+09,5.751460e+08,2.022202e+09,1.298340e+09,3.722262e+09,3.277112e+09,251262.0,1794598.0,262986.0,50338.0,11.896950,8.146336,"POLYGON ((-80.51860 40.63695, -80.51860 39.722..."
48,Wisconsin,1.913243e+10,1.385676e+09,8.204953e+09,9.541802e+09,1.936443e+10,1.523472e+10,1158444.0,8230009.0,1263431.0,103554.0,63.018816,104.641102,"POLYGON ((-90.41543 46.56848, -90.22921 46.508..."
49,Wyoming,1.666253e+09,2.203290e+08,9.526130e+08,4.933110e+08,1.641255e+09,1.456590e+09,78466.0,482540.0,83633.0,8502.0,7.824441,10.912464,"POLYGON ((-109.08084 45.00207, -105.91517 45.0..."

## Create poverty to expenditure metric
Revenue Per Student in Poverty: Higher values indicate more funding is available per student in poverty, which might suggest better resource allocation for high-need areas.

In [71]:
df['PSI'] = (
    df['Total Revenue'] / df['Number of Students']
) / (df['Estimated School Age Poverty'] / df['Estimated School Age Population'])

df['Revenue per Student'] = df['Total Revenue'] / df['Number of Students']
df['Poverty Share'] = df['Estimated School Age Poverty'] / df['Estimated School Age Population']

#df['Poverty_Adjusted_Revenue'] = df['Poverty_Adjusted_Revenue'].apply(lambda x: x * 1e-6)
df.head()

,name,Total Revenue,Total Fedreal Revenue,Total State Revenue,Total Local Revenue,Total Expenditure,Total Current Expenditures Education,Number of Students,Estimated Total Population,Estimated School Age Population,Estimated School Age Poverty,School Age Poverty Share,School Age Share Population,geometry,PSI,Revenue per Student,Poverty Share
0,Alabama,1.462399e+10,2.178050e+09,7.862680e+09,4.583262e+09,1.371499e+10,1.183144e+10,1045118.0,7368282.0,1190528.0,221740.0,46.864622,35.642442,"POLYGON ((-87.35930 35.00118, -85.60667 34.984...",75127.023740,13992.670684,0.186253
1,Alaska,1.031222e+09,1.851580e+08,7.027960e+08,1.432680e+08,1.037706e+09,9.819600e+08,66356.0,249366.0,42938.0,4692.0,8.855286,7.943110,"MULTIPOLYGON (((-131.60202 55.11798, -131.5691...",142218.397053,15540.749895,0.109274
2,Arizona,1.606651e+10,2.799010e+09,6.222061e+09,7.045438e+09,1.574263e+10,1.297759e+10,1340338.0,13693867.0,1913294.0,287185.0,56.863344,43.199131,"POLYGON ((-109.04250 37.00026, -109.04798 31.3...",79859.603257,11986.908526,0.150100
3,Arkansas,9.879550e+09,1.541200e+09,4.496606e+09,3.841744e+09,9.749658e+09,8.378818e+09,766148.0,5047096.0,848330.0,152132.0,79.644082,63.900284,"POLYGON ((-94.47384 36.50186, -90.15254 36.496...",71906.597980,12895.093376,0.179331
4,California,1.205338e+11,1.545904e+10,6.633966e+10,3.873512e+10,1.116487e+11,9.345144e+10,6696239.0,53857316.0,7889224.0,1093610.0,164.130942,153.955398,"POLYGON ((-123.23326 42.00619, -122.37885 42.0...",129852.334029,18000.225500,0.138621

In [111]:
df.Poverty_Adjusted_Revenue.min()

49239.26476988689

In [108]:
df.drop(index=15, inplace=True)

In [72]:
df.to_file('state_FINAL.geojson')

In [27]:
df.Poverty_Adjusted_Revenue.max()

0.028580043286107523

In [16]:
df.to_file('state_FINAL.geojson')

# Now do this by District

In [29]:
df = gpd.read_file('finance_poverty_school_districts_FINAL.geojson')
df.head()

,STATEFP,NAME,GEOID,LOGRADE,HIGRADE,fips_x,leaid_x,Total Revenue,Total Fedreal Revenue,Total State Revenue,...,Estimated total population ages 5-17,Estimated population ages 5-17 in poverty,leaid_y,Share of school-age population (ages 5-17) in poverty,Share of population that is school age (ages 5-17),index_right,id,name,density,geometry
0,26,Quincy Community School District,2629250,PK,12,26.0,2629250,14841000.0,2240000.0,9954000.0,...,1481.0,253.0,2629250,0.170831,0.194357,NaN,None,None,NaN,"MULTIPOLYGON (((-84.91766 41.76374, -84.91254 ..."
1,26,Imlay City Community Schools,2619100,PK,12,26.0,2619100,26938000.0,2562000.0,17576000.0,...,1950.0,195.0,2619100,0.100000,0.162041,22.0,26,Michigan,173.9,"POLYGON ((-83.21305 42.99102, -83.21287 42.991..."
2,26,Bark River-Harris School District,2604020,KG,12,26.0,2604020,8904000.0,1223000.0,6626000.0,...,513.0,70.0,2604020,0.136452,0.169307,22.0,26,Michigan,173.9,"POLYGON ((-87.49286 45.94106, -87.49281 45.945..."
3,26,Spring Lake Public Schools,2632550,PK,12,26.0,2632550,38617000.0,2168000.0,21923000.0,...,2487.0,91.0,2632550,0.036590,0.184236,22.0,26,Michigan,173.9,"POLYGON ((-86.21542 43.10232, -86.21541 43.103..."
4,26,Ithaca Public Schools,2619580,KG,12,26.0,2619580,14627000.0,1536000.0,9315000.0,...,1172.0,139.0,2619580,0.118601,0.165187,22.0,26,Michigan,173.9,"MULTIPOLYGON (((-84.43447 43.33140, -84.43447 ..."

In [25]:
df.name.isnull().sum()

4878

In [30]:
df.columns = df.columns.str.replace('_', ' ')
df.head()

,STATEFP,NAME,GEOID,LOGRADE,HIGRADE,fips x,leaid x,Total Revenue,Total Fedreal Revenue,Total State Revenue,...,Estimated total population ages 5-17,Estimated population ages 5-17 in poverty,leaid y,Share of school-age population (ages 5-17) in poverty,Share of population that is school age (ages 5-17),index right,id,name,density,geometry
0,26,Quincy Community School District,2629250,PK,12,26.0,2629250,14841000.0,2240000.0,9954000.0,...,1481.0,253.0,2629250,0.170831,0.194357,NaN,None,None,NaN,"MULTIPOLYGON (((-84.91766 41.76374, -84.91254 ..."
1,26,Imlay City Community Schools,2619100,PK,12,26.0,2619100,26938000.0,2562000.0,17576000.0,...,1950.0,195.0,2619100,0.100000,0.162041,22.0,26,Michigan,173.9,"POLYGON ((-83.21305 42.99102, -83.21287 42.991..."
2,26,Bark River-Harris School District,2604020,KG,12,26.0,2604020,8904000.0,1223000.0,6626000.0,...,513.0,70.0,2604020,0.136452,0.169307,22.0,26,Michigan,173.9,"POLYGON ((-87.49286 45.94106, -87.49281 45.945..."
3,26,Spring Lake Public Schools,2632550,PK,12,26.0,2632550,38617000.0,2168000.0,21923000.0,...,2487.0,91.0,2632550,0.036590,0.184236,22.0,26,Michigan,173.9,"POLYGON ((-86.21542 43.10232, -86.21541 43.103..."
4,26,Ithaca Public Schools,2619580,KG,12,26.0,2619580,14627000.0,1536000.0,9315000.0,...,1172.0,139.0,2619580,0.118601,0.165187,22.0,26,Michigan,173.9,"MULTIPOLYGON (((-84.43447 43.33140, -84.43447 ..."

In [31]:
df.drop(columns=['id','density', 'index right', 'GEOID','leaid x','exp current resa', 'district name','leaid y'], inplace=True)
df.rename(columns={
    'name': 'State Name',
    'NAME': 'District Name',
    'LOGRADE': 'Lowest Grade',
    'HIGRADE': 'Highest Grade',
    'rev local total': 'Total Local Revenue'
}, inplace=True)

In [50]:
import numpy as np
df.loc[df['Estimated population ages 5-17 in poverty'] == 0, 'Estimated population ages 5-17 in poverty'] = np.nan

In [ ]:
# Mask to exclude rows where the number of students is 0
mask = df['Number of students attending school within the reporting local education agency'] > 0

df.loc[mask, 'PSI'] = (
    df.loc[mask, 'Total Revenue'] / df.loc[mask, 'Number of students attending school within the reporting local education agency']
) / (df.loc[mask, 'Estimated population ages 5-17 in poverty'] / df.loc[mask, 'Estimated total population ages 5-17'])

# df.loc[~mask, 'Poverty_Adjusted_Revenue'] = float('nan')


# valid_mask = df['Poverty_Adjusted_Revenue'].notna()

# df.loc[valid_mask, 'Normalized_Revenue'] = (df.loc[valid_mask, 'Poverty_Adjusted_Revenue'] - df.loc[valid_mask, 'Poverty_Adjusted_Revenue'].min()) / (
#     df.loc[valid_mask, 'Poverty_Adjusted_Revenue'].max() - df.loc[valid_mask, 'Poverty_Adjusted_Revenue'].min()
# )

# df.loc[~valid_mask, 'Normalized_Revenue'] = float('nan')

In [52]:
df['Revenue per Student'] = df['Total Revenue'] / df['Number of students attending school within the reporting local education agency']

In [53]:
df.head()

,STATEFP,District Name,Lowest Grade,Highest Grade,fips x,Total Revenue,Total Fedreal Revenue,Total State Revenue,Total Local Revenue,Total Expenditure,...,fips y,Estimated total population,Estimated total population ages 5-17,Estimated population ages 5-17 in poverty,Share of school-age population (ages 5-17) in poverty,Share of population that is school age (ages 5-17),State Name,geometry,PSI,Revenue per Student
0,26,Quincy Community School District,PK,12,26.0,14841000.0,2240000.0,9954000.0,2647000.0,12631000.0,...,26.0,7620.0,1481.0,253.0,0.170831,0.194357,None,"MULTIPOLYGON (((-84.91766 41.76374, -84.91254 ...",74892.738858,12793.965517
1,26,Imlay City Community Schools,PK,12,26.0,26938000.0,2562000.0,17576000.0,6800000.0,31667000.0,...,26.0,12034.0,1950.0,195.0,0.100000,0.162041,Michigan,"POLYGON ((-83.21305 42.99102, -83.21287 42.991...",145218.328841,14521.832884
2,26,Bark River-Harris School District,KG,12,26.0,8904000.0,1223000.0,6626000.0,1055000.0,9502000.0,...,26.0,3030.0,513.0,70.0,0.136452,0.169307,Michigan,"POLYGON ((-87.49286 45.94106, -87.49281 45.945...",95820.264317,13074.889868
3,26,Spring Lake Public Schools,PK,12,26.0,38617000.0,2168000.0,21923000.0,14526000.0,33337000.0,...,26.0,13499.0,2487.0,91.0,0.036590,0.184236,Michigan,"POLYGON ((-86.21542 43.10232, -86.21541 43.103...",436291.806168,15964.034725
4,26,Ithaca Public Schools,KG,12,26.0,14627000.0,1536000.0,9315000.0,3776000.0,12421000.0,...,26.0,7095.0,1172.0,139.0,0.118601,0.165187,Michigan,"MULTIPOLYGON (((-84.43447 43.33140, -84.43447 ...",118245.266491,14023.969319

In [57]:
m = df.PSI.max()
df[df.PSI == m]

,STATEFP,District Name,Lowest Grade,Highest Grade,fips x,Total Revenue,Total Fedreal Revenue,Total State Revenue,Total Local Revenue,Total Expenditure,...,fips y,Estimated total population,Estimated total population ages 5-17,Estimated population ages 5-17 in poverty,Share of school-age population (ages 5-17) in poverty,Share of population that is school age (ages 5-17),State Name,geometry,PSI,Revenue per Student
23950,33,New Castle School District,KG,12,33.0,2219000.0,27000.0,1414000.0,778000.0,2133000.0,...,33.0,1018.0,101.0,1.0,0.009901,0.099214,None,"POLYGON ((-70.73838 43.07089, -70.73831 43.071...",6.225528e+06,61638.888889

In [56]:
df.drop_duplicates(inplace=True)
test = df[df['District Name'] != 'Aleutian Region School District']
test.to_file('districts.geojson')